#!/usr/bin/env bash
# Install (or update) the `cato` CLI — PrudAI's command line interface for CATO.
#
#   curl -fsSL https://raw.githubusercontent.com/BCJonkhout/twenty-crm-mcp-server/main/install.sh | bash
#
# Idempotent: run it again to update to the latest main. It installs three things
# and nothing else:
#   1. bun, if it is missing (into ~/.bun — the official installer, unprivileged)
#   2. this repository, into ~/.cato
#   3. a `cato` shim in ~/.local/bin
#
# It never writes a credential. The key is a separate, deliberate step at the end,
# because a secret that arrives by pipe ends up in scrollback and shell history.
set -euo pipefail

REPO_URL="${CATO_REPO_URL:-https://github.com/BCJonkhout/twenty-crm-mcp-server.git}"
CATO_HOME="${CATO_HOME:-$HOME/.cato}"
BIN_DIR="${CATO_BIN_DIR:-$HOME/.local/bin}"
BRANCH="${CATO_BRANCH:-main}"

info() { printf '\033[1;34m::\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m!!\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31mxx\033[0m %s\n' "$*" >&2; exit 1; }
have() { command -v "$1" >/dev/null 2>&1; }

# ---------------------------------------------------------------- platform ---
case "$(uname -s 2>/dev/null || echo unknown)" in
  Linux*)   PLATFORM=linux ;;
  Darwin*)  PLATFORM=macos ;;
  MINGW*|MSYS*|CYGWIN*)
    die "This installer needs a POSIX shell. On Windows, run it inside WSL (wsl --install, then reopen the terminal and paste the same command). Git Bash is not enough: bun's installer wants a real Linux or macOS environment." ;;
  *) PLATFORM=unknown ;;
esac
grep -qi microsoft /proc/version 2>/dev/null && PLATFORM=wsl
info "Platform: $PLATFORM"

have git || die "git is missing. Install it first (macOS: xcode-select --install; Debian/Ubuntu: sudo apt install git)."

# -------------------------------------------------------------------- bun ---
# The CLI runs TypeScript directly, so bun is the runtime, not a build tool.
if have bun; then
  info "bun: $(bun --version) (already installed)"
elif [ -x "$HOME/.bun/bin/bun" ]; then
  export PATH="$HOME/.bun/bin:$PATH"
  info "bun: $(bun --version) (found in ~/.bun, not yet on PATH)"
else
  info "bun is missing — installing it from bun.sh into ~/.bun"
  have curl || die "curl is missing and bun's installer needs it."
  curl -fsSL https://bun.sh/install | bash >/dev/null 2>&1 || die "bun install failed. Install it by hand from https://bun.sh and re-run this script."
  export PATH="$HOME/.bun/bin:$PATH"
  have bun || die "bun installed but is not on PATH. Open a new terminal and re-run this script."
  info "bun: $(bun --version) (installed)"
fi

# ------------------------------------------------------------------- repo ---
if [ -d "$CATO_HOME/.git" ]; then
  info "Updating $CATO_HOME"
  git -C "$CATO_HOME" fetch --quiet origin "$BRANCH"
  # Hard reset: this checkout is a delivery mechanism, not a workspace. Anyone
  # developing the CLI does that in their own clone.
  git -C "$CATO_HOME" reset --hard --quiet "origin/$BRANCH"
elif [ -e "$CATO_HOME" ]; then
  die "$CATO_HOME exists but is not a git checkout. Move it aside and re-run."
else
  info "Cloning into $CATO_HOME"
  git clone --quiet --depth 1 --branch "$BRANCH" "$REPO_URL" "$CATO_HOME"
fi

info "Installing dependencies"
(cd "$CATO_HOME" && bun install --silent) || die "bun install failed in $CATO_HOME."

# ------------------------------------------------------------------- shim ---
# A shim rather than a symlink to cli/src/index.ts: the symlink only works when
# bun happens to be on PATH, which is exactly what fails in cron, CI and any
# non-login shell. The shim finds bun itself.
mkdir -p "$BIN_DIR"
cat > "$BIN_DIR/cato" <<SHIM
#!/usr/bin/env bash
# Generated by the cato installer. Re-run the installer to regenerate.
CATO_HOME="\${CATO_HOME:-$CATO_HOME}"
if command -v bun >/dev/null 2>&1; then BUN=bun
elif [ -x "\$HOME/.bun/bin/bun" ]; then BUN="\$HOME/.bun/bin/bun"
else echo "cato: bun not found. Re-run the cato installer." >&2; exit 127; fi
exec "\$BUN" "\$CATO_HOME/cli/src/index.ts" "\$@"
SHIM
chmod +x "$BIN_DIR/cato"
info "Installed $BIN_DIR/cato"

# ------------------------------------------------------------------- PATH ---
PATH_OK=no
case ":$PATH:" in *":$BIN_DIR:"*) PATH_OK=yes ;; esac
if [ "$PATH_OK" = no ]; then
  RC=""
  case "$(basename "${SHELL:-/bin/bash}")" in
    zsh)  RC="$HOME/.zshrc" ;;
    bash) [ "$PLATFORM" = macos ] && RC="$HOME/.bash_profile" || RC="$HOME/.bashrc" ;;
    fish) RC="$HOME/.config/fish/config.fish" ;;
  esac
  LINE="export PATH=\"$BIN_DIR:\$PATH\""
  [ "$(basename "${SHELL:-}")" = fish ] && LINE="fish_add_path $BIN_DIR"
  if [ -n "$RC" ] && grep -qF "$BIN_DIR" "$RC" 2>/dev/null; then
    # Already configured; this shell just has not read the profile yet.
    info "$BIN_DIR is already in $RC — open a new terminal to pick it up."
  elif [ -n "$RC" ]; then
    mkdir -p "$(dirname "$RC")"
    printf '\n# added by the cato installer\n%s\n' "$LINE" >> "$RC"
    info "Added $BIN_DIR to your PATH in $RC — open a new terminal, or run: $LINE"
  else
    warn "$BIN_DIR is not on your PATH and I could not identify your shell profile."
    warn "Add this line to it yourself:"
    warn "  $LINE"
  fi
  export PATH="$BIN_DIR:$PATH"
fi

# ------------------------------------------------------------------ check ---
VERSION="$("$BIN_DIR/cato" --version 2>/dev/null || true)"
[ -n "$VERSION" ] || die "cato was installed but will not run. Report the output of: $BIN_DIR/cato --version"
info "cato $VERSION is installed."

echo
# `auth status` exits 0 even with no credential at all — it is a report, not a
# check — so read the resolved source instead of the exit code.
CRED_SOURCE="$("$BIN_DIR/cato" auth status --json 2>/dev/null | sed -n 's/.*"source": *"\([a-z-]*\)".*/\1/p' | head -1)"
if [ -n "$CRED_SOURCE" ] && [ "$CRED_SOURCE" != none ]; then
  echo "You already have a working credential:"
  "$BIN_DIR/cato" auth status || true
  echo
  echo "Next:  cato guide          # how to drive this from a coding agent"
else
  cat <<'NEXT'
One step left: a key. Ask Beau for a CATO API key (he creates it with
`cato auth create`, scoped to the least-privilege role), then store it:

    cato auth set --stdin --set-default
    <paste the key, press Enter, then Ctrl-D>

The key is written to ~/.config/cato/credentials.json with mode 0600 and is
never echoed. Do not paste it into a chat, a ticket, or a commit.

Then:
    cato auth status          # what am I holding, and what may it do
    cato guide                # how a coding agent should use this
    cato tasks list --limit 5 # the task board
NEXT
fi
echo
echo "Update later by re-running this installer. Uninstall: rm -rf $CATO_HOME $BIN_DIR/cato"
