#!/usr/bin/env bun
// Generate cli/openapi/cato.yaml from the LIVE CATO OpenAPI document.
//
// Twenty already publishes a complete OpenAPI 3.1 document at
// GET {baseUrl}/rest/open-api/core (~700 kB, 242 paths, every object in the
// workspace including custom marketing tables). Hand-writing a spec against
// that would guarantee drift, so this script *narrows* the live document
// instead of re-describing it:
//
//   * keep only the four objects we want to expose to an external consumer
//     (people, companies, opportunities, notes);
//   * keep the verbs the CLI exposes; writes are described, not hidden, by
//     construction, not by convention;
//   * carry the transitive closure of every referenced component so the file
//     stays self-contained;
//   * drop batch/merge/duplicates/groupBy routes and every other object.
//
// Usage:
//   CATO_API_KEY=... bun run cli/scripts/generate-openapi.ts
//   CATO_API_KEY=... bun run cli/scripts/generate-openapi.ts --out other.yaml

import { DEFAULT_BASE_URL } from "../src/config.ts";

type Json = null | boolean | number | string | Json[] | { [key: string]: Json };

import { MARKETING_PATHS } from "./marketing-paths.ts";

const EXPOSED_OBJECTS = ["people", "companies", "opportunities", "notes"] as const;

/** Paths we keep, in output order. Everything else is dropped. */
function keptPaths(): string[] {
  return EXPOSED_OBJECTS.flatMap((o) => [`/${o}`, `/${o}/{id}`]);
}

const OVERVIEW = `The surface of PrudAI's Twenty CRM instance ("CATO").

Generated by cli/scripts/generate-openapi.ts. The core objects are taken from
the live CATO document (GET /rest/open-api/core), so their field names, enum
values and composite shapes are the real ones and cannot drift. The
/marketing/* routes are a custom controller in our Twenty fork and do not
appear in that document; they are described in cli/scripts/marketing-paths.ts
and must be kept in step with the controllers by hand.

WHAT IS IN HERE
  * people, companies, opportunities, notes — list, get, create, update, delete;
  * the full /marketing/* module: campaigns, company targets, contact research,
    contact selection candidates, members, review queue, assets and sending.

WHAT IS LEFT OUT
  * the /batch/*, /merge, /duplicates and /groupBy routes;
  * every other object in the workspace, including messages,
    messageParticipants, connectedAccounts and calendarEvents — those carry
    e-mail content and mailbox metadata;
  * the metadata API (/rest/metadata/*) and the GraphQL endpoints.

SENDING MAIL
  Nothing here sends mail on its own. A campaign is created disabled with
  generation off and no members, and CATO refuses to dispatch a touchpoint
  whose approvalState is not 'approved'. Approving is a deliberate human step;
  there is no auto-approve route.

AUTHENTICATION
  Bearer token in the Authorization header — a Twenty API key, or a user
  session token.

  IMPORTANT — read this before issuing a key. Every API key must carry a role,
  and a role is only attachable to an API key when canBeAssignedToApiKeys is
  true. Today the ONLY such role in this workspace is Admin, which grants read,
  write, delete and all settings — and since server-commit 3c570e37 it also
  grants access to the marketing module. A key issued today therefore cannot be
  read-only, and can approve and send campaign mail. Creating a restricted role
  first is the fix. Verify with: cato auth roles`;

interface OpenApiDoc {
  openapi: string;
  info: Record<string, Json>;
  servers?: Json;
  paths: Record<string, Record<string, Json>>;
  components?: {
    schemas?: Record<string, Json>;
    parameters?: Record<string, Json>;
    responses?: Record<string, Json>;
    securitySchemes?: Record<string, Json>;
  };
  security?: Json;
  tags?: Json;
}

async function fetchLiveSpec(baseUrl: string, apiKey: string): Promise<OpenApiDoc> {
  const res = await fetch(`${baseUrl.replace(/\/$/, "")}/rest/open-api/core`, {
    headers: { Authorization: `Bearer ${apiKey}` },
  });
  if (!res.ok) {
    throw new Error(`Could not fetch the live CATO OpenAPI document: HTTP ${res.status}`);
  }
  return (await res.json()) as OpenApiDoc;
}

/** Collect every "#/components/<kind>/<name>" reference reachable from `node`. */
function collectRefs(node: Json, out: Set<string>): void {
  if (node === null || typeof node !== "object") return;
  if (Array.isArray(node)) {
    for (const item of node) collectRefs(item, out);
    return;
  }
  for (const [key, value] of Object.entries(node)) {
    if (key === "$ref" && typeof value === "string" && value.startsWith("#/components/")) {
      out.add(value);
    } else {
      collectRefs(value, out);
    }
  }
}

function resolveRef(doc: OpenApiDoc, ref: string): Json | undefined {
  const [, , kind, name] = ref.split("/");
  if (kind === "schemas") return doc.components?.schemas?.[name!];
  if (kind === "parameters") return doc.components?.parameters?.[name!];
  if (kind === "responses") return doc.components?.responses?.[name!];
  if (kind === "securitySchemes") return doc.components?.securitySchemes?.[name!];
  return undefined;
}

export function narrowSpec(live: OpenApiDoc, baseUrl: string): OpenApiDoc {
  const paths: Record<string, Record<string, Json>> = {};

  for (const path of keptPaths()) {
    const original = live.paths[path];
    if (!original) continue;
    const kept: Record<string, Json> = {};
    for (const [method, operation] of Object.entries(original)) {
      // Core objects: reads plus the write verbs the CLI actually exposes.
      if (!["get", "post", "patch", "delete"].includes(method.toLowerCase())) continue;
      kept[method] = operation;
    }
    if (Object.keys(kept).length > 0) paths[path] = kept;
  }

  if (Object.keys(paths).length === 0) {
    throw new Error("Narrowing produced no paths — the live document layout changed. Inspect it before shipping.");
  }

  // The marketing module is our own controller and is absent from Twenty's
  // document, so it is described by hand and merged in here.
  for (const [path, methods] of Object.entries(MARKETING_PATHS)) {
    paths[path] = methods as Record<string, Json>;
  }

  // Transitive $ref closure, so the generated file resolves standalone.
  const refs = new Set<string>();
  collectRefs(paths as unknown as Json, refs);
  let frontier = [...refs];
  while (frontier.length > 0) {
    const next: string[] = [];
    for (const ref of frontier) {
      const target = resolveRef(live, ref);
      if (target === undefined) continue;
      const found = new Set<string>();
      collectRefs(target, found);
      for (const f of found) {
        if (!refs.has(f)) { refs.add(f); next.push(f); }
      }
    }
    frontier = next;
  }

  const schemas: Record<string, Json> = {};
  const parameters: Record<string, Json> = {};
  const responses: Record<string, Json> = {};
  for (const ref of [...refs].sort()) {
    const [, , kind, name] = ref.split("/");
    const target = resolveRef(live, ref);
    if (target === undefined) {
      throw new Error(`Referenced component ${ref} is missing from the live document — refusing to emit a spec with a dangling $ref.`);
    }
    if (kind === "schemas") schemas[name!] = target;
    else if (kind === "parameters") parameters[name!] = target;
    else if (kind === "responses") responses[name!] = target;
  }

  return {
    openapi: live.openapi ?? "3.1.1",
    info: {
      title: "CATO — PrudAI CRM",
      version: String(live.info?.version ?? "1.0.0"),
      description: OVERVIEW,
    },
    servers: [{ url: `${baseUrl.replace(/\/$/, "")}/rest/`, description: "CATO production" }],
    security: [{ bearerAuth: [] }],
    paths,
    components: {
      securitySchemes: {
        bearerAuth: {
          type: "http",
          scheme: "bearer",
          bearerFormat: "JWT",
          description: "Twenty API key. See `cato auth roles` for what a key can actually do.",
        },
      },
      parameters,
      responses,
      schemas,
    },
  };
}

// ---- minimal deterministic YAML emitter -----------------------------------
// Avoids a dependency for a job that is JSON-in, YAML-out.

const PLAIN_SAFE = /^[A-Za-z0-9_][A-Za-z0-9_.\-/ ]*$/;

/** Literal block scalar, keeping the string's own relative indentation intact. */
function yamlBlock(value: string, indent: number): string {
  const pad = "  ".repeat(indent);
  const body = value.split("\n").map((l) => (l ? `${pad}${l}` : "")).join("\n");
  return `|-\n${body}`;
}

function yamlScalar(value: null | boolean | number | string): string {
  if (value === null) return "null";
  if (typeof value === "boolean" || typeof value === "number") return String(value);
  if (value === "") return '""';
  const reserved = ["true", "false", "null", "yes", "no", "on", "off", "~"];
  if (PLAIN_SAFE.test(value) && !reserved.includes(value.toLowerCase()) && !/^\d+(\.\d+)?$/.test(value)) {
    return value;
  }
  return JSON.stringify(value);
}

function yamlKey(key: string): string {
  // Numeric-looking keys must stay strings: an HTTP status key emitted bare
  // parses as the integer 400, and `$ref: '#/components/responses/400'` then
  // dangles against a document whose key is a number.
  if (/^\d+$/.test(key)) return JSON.stringify(key);
  return PLAIN_SAFE.test(key) ? key : JSON.stringify(key);
}

export function toYaml(node: Json, indent = 0): string {
  const pad = "  ".repeat(indent);

  if (node === null || typeof node !== "object") {
    if (typeof node === "string" && node.includes("\n")) return yamlBlock(node, indent);
    return yamlScalar(node);
  }

  if (Array.isArray(node)) {
    if (node.length === 0) return "[]";
    return node
      .map((item) => {
        if (item !== null && typeof item === "object") {
          const rendered = toYaml(item, indent + 1);
          return `${pad}- ${rendered.slice((indent + 1) * 2)}`;
        }
        if (typeof item === "string" && item.includes("\n")) {
          return `${pad}- ${yamlBlock(item, indent + 1)}`;
        }
        return `${pad}- ${yamlScalar(item)}`;
      })
      .join("\n");
  }

  const entries = Object.entries(node);
  if (entries.length === 0) return "{}";
  return entries
    .map(([key, value]) => {
      if (value !== null && typeof value === "object" && !Array.isArray(value) && Object.keys(value).length === 0) {
        return `${pad}${yamlKey(key)}: {}`;
      }
      if (Array.isArray(value) && value.length === 0) {
        return `${pad}${yamlKey(key)}: []`;
      }
      if (value !== null && typeof value === "object") {
        return `${pad}${yamlKey(key)}:\n${toYaml(value, indent + 1)}`;
      }
      if (typeof value === "string" && value.includes("\n")) {
        return `${pad}${yamlKey(key)}: ${yamlBlock(value, indent + 1)}`;
      }
      return `${pad}${yamlKey(key)}: ${yamlScalar(value)}`;
    })
    .join("\n");
}

if (import.meta.main) {
  const args = process.argv.slice(2);
  const outIndex = args.indexOf("--out");
  const outPath = outIndex === -1 ? new URL("../openapi/cato.yaml", import.meta.url).pathname : args[outIndex + 1]!;

  const apiKey = process.env.CATO_API_KEY;
  if (!apiKey) {
    console.error("CATO_API_KEY is required to read the live OpenAPI document from CATO.");
    process.exit(2);
  }
  const baseUrl = process.env.CATO_BASE_URL ?? DEFAULT_BASE_URL;

  const live = await fetchLiveSpec(baseUrl, apiKey);
  const narrowed = narrowSpec(live, baseUrl);
  const header = [
    "# GENERATED FILE — do not edit by hand.",
    "# Source : GET " + baseUrl.replace(/\/$/, "") + "/rest/open-api/core (live CATO instance)",
    "# Script : bun run cli/scripts/generate-openapi.ts",
    "# Regenerate after any CRM schema change; do not patch this file directly.",
    "",
  ].join("\n");

  await Bun.write(outPath, `${header}${toYaml(narrowed as unknown as Json)}\n`);
  const pathCount = Object.keys(narrowed.paths).length;
  const schemaCount = Object.keys(narrowed.components?.schemas ?? {}).length;
  console.log(`Wrote ${outPath}: ${pathCount} paths, ${schemaCount} schemas (from ${Object.keys(live.paths).length} live paths).`);
}
